title: Yohanssen Pratama
baseURL: https://example.com
theme: hugo-researcher
disableKinds:
  - taxonomy
  - term
enableEmoji: yes
math: no
googleAnalytics: ''
params:
  author: Olivier Roques
  description: A simple monospaced resume theme for Hugo.
  favicon: favicon.ico
  footer:
    text: By Olivier Roques
    url: https://github.com/ojroques/hugo-researcher
  logo: ''
  socialIcons:
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/
    - icon: fas fa-envelope
      title: E-mail
      url: mailto:mail@example.com
  style:
    avatarSize: 90px
    colorBlack: '#222222'
    colorRed: '#dc3545'
    fontFamily: Inconsolata
    pageWidth: 750px
permalinks:
  /: /:filename
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Resume
      pre: '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill"
        fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
        d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2
        2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0
        1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1
        1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
      url: /resume.pdf
      weight: 2
    - name: Contact
      url: /contact
      weight: 3
markup:
  goldmark:
    renderer:
      unsafe: yes
